const artistData = {
  name: 'Eminem',
  id: 38661,
  resource_url: 'https://api.discogs.com/artists/38661',
  uri: 'https://www.discogs.com/artist/38661-Eminem',
  releases_url: 'https://api.discogs.com/artists/38661/releases',
  images: [
    {
      type: 'primary',
      uri: '',
      resource_url: '',
      uri150: '',
      width: 600,
      height: 337,
    },
    {
      type: 'secondary',
      uri: '',
      resource_url: '',
      uri150: '',
      width: 600,
      height: 600,
    },
    {
      type: 'secondary',
      uri: '',
      resource_url: '',
      uri150: '',
      width: 348,
      height: 450,
    },
    {
      type: 'secondary',
      uri: '',
      resource_url: '',
      uri150: '',
      width: 300,
      height: 500,
    },
    {
      type: 'secondary',
      uri: '',
      resource_url: '',
      uri150: '',
      width: 452,
      height: 652,
    },
    {
      type: 'secondary',
      uri: '',
      resource_url: '',
      uri150: '',
      width: 600,
      height: 600,
    },
    {
      type: 'secondary',
      uri: '',
      resource_url: '',
      uri150: '',
      width: 600,
      height: 607,
    },
    {
      type: 'secondary',
      uri: '',
      resource_url: '',
      uri150: '',
      width: 220,
      height: 170,
    },
  ],
  realname: 'Marshall Bruce Mathers III',
  profile:
    "Marshall Bruce Mathers III (born October 17, 1972, St. Joseph, Missouri), known by his primary stage name Eminem (stylized as EMINƎM), or by his alter ego Slim Shady, is an American rapper and record producer who grew up in Detroit, Michigan. He began his professional music career as a member of Soul Intent along with Proof in 1992. He also started his first record label with his group that same year called Mashin' Duck Records.",
  urls: [
    'http://www.eminem.com',
    'http://www.instagram.com/eminem',
    'http://twitter.com/Eminem',
    'http://www.facebook.com/eminem',
    'http://www.imdb.com/name/nm0004896',
    'http://www.myspace.com/eminem',
    'https://www.youtube.com/user/EminemMusic',
    'https://www.youtube.com/user/EminemVEVO',
    'http://eminem.tumblr.com',
    'http://en.wikipedia.org/wiki/Eminem',
    'http://equipboard.com/pros/eminem',
    'https://genius.com/eminem',
  ],
  namevariations: [
    'E. Minem',
    'Em',
    'Emenem',
    'Emiem',
    'Emine',
    'Eminem Show',
    'Eminen',
    'EMINƎM',
    'Eminien',
    'Enimen',
    'M & M',
    'M.N.M',
    'M&M',
    'MNM',
    'エミネム',
    '埃米·納姆',
    '阿姆',
  ],
  aliases: [
    {
      id: 108184,
      name: 'Slim Shady',
      resource_url: 'https://api.discogs.com/artists/108184',
    },
    {
      id: 644153,
      name: 'Marshall Mathers',
      resource_url: 'https://api.discogs.com/artists/644153',
    },
    {
      id: 787714,
      name: 'Ken Kaniff',
      resource_url: 'https://api.discogs.com/artists/787714',
    },
  ],
  data_quality: 'Correct',
};
